"""TOY_01 with 4WD + prismatic suspension joints (4 wheels).

Built from the patched physics USD `f1tenth_mid360_physics_suspended.usd`
(generated by `scripts/patch_toy01_suspension.py`). The original
`f1tenth_mid360_physics.usd` and `TOY_01_chassis.usd` are untouched.

Joint topology (12 joints):
    base_link
      ├── front_left_steering_joint  (revolute Z, ±0.6 rad)
      │    └── front_left_steering_link
      │         ├── front_left_wheel_link_sus_joint  (prismatic Z, ±15mm, k=2000)
      │         │    └── front_left_wheel_link_sus_link
      │         └── front_left_wheel_joint           (revolute Y, free)
      │              └── front_left_wheel_link
      ├── front_right_*  (mirror)
      ├── rear_left_wheel_link_sus_joint  (prismatic Z, ±15mm)
      │    └── rear_left_wheel_link_sus_link
      ├── rear_left_wheel_joint           (revolute Y)
      │    └── rear_left_wheel_link
      ├── rear_right_*  (mirror)
      ├── lidar_joint   (fixed)
      └── camera_joint  (fixed)
"""

from __future__ import annotations

import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

_F1TENTH_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "f1tenth_mid360", "assets", "configuration",
)
USD_PATH = os.path.normpath(
    os.path.join(_F1TENTH_DIR, "f1tenth_mid360_physics_suspended.usd")
)

# Same physical dims as f1tenth_mid360
WHEELBASE = 0.2255
TRACK_WIDTH = 0.200
WHEEL_RADIUS = 0.0365
MAX_STEER = 0.6

TOY01_4WD_SUS_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=USD_PATH,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            rigid_body_enabled=True,
            max_linear_velocity=20.0,
            max_angular_velocity=2000.0,
            max_depenetration_velocity=10.0,
            enable_gyroscopic_forces=True,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=24,
            solver_velocity_iteration_count=8,
            sleep_threshold=0.005,
            stabilization_threshold=0.001,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.06),
        joint_pos={".*": 0.0},
    ),
    actuators={
        "steering": ImplicitActuatorCfg(
            joint_names_expr=["front_.*_steering_joint"],
            effort_limit_sim=500.0,
            stiffness=8000.0,
            damping=200.0,
        ),
        # ── 4WD: drive ALL four wheel joints ──
        "drive": ImplicitActuatorCfg(
            joint_names_expr=[".*_wheel_joint$"],
            effort_limit_sim=8.0,    # 4WD → split torque per wheel
            stiffness=0.0,
            damping=20.0,
        ),
        # Suspension joints — passive spring (the USD has DriveAPI:linear
        # set to k=2000, c=80 so PhysX handles the spring force directly).
        # We keep stiffness/damping=0 here so this actuator doesn't fight.
        "suspension": ImplicitActuatorCfg(
            joint_names_expr=[".*_sus_joint"],
            effort_limit_sim=0.0,
            stiffness=0.0,
            damping=0.0,
        ),
    },
)

__all__ = [
    "TOY01_4WD_SUS_CFG",
    "USD_PATH",
    "WHEELBASE",
    "TRACK_WIDTH",
    "WHEEL_RADIUS",
    "MAX_STEER",
]
